apiVersion: apps/v1
kind: Deployment
metadata:
  name: stresser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stresser
  template:
    metadata:
      labels:
        app: stresser
    spec:
      containers:
        - name: stresser
          image: polinux/stress-ng
          command: ["stress-ng"]
          args: ["--cpu", "4", "--timeout", "60s"]