name: Testing

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install --upgrade pip
          
      - name: Install project dependencies
        run: pip install -r requirements.txt

      - name: Run linter
        run: |
          pylint main.py

      - name: Run tests
        run: python -m unittest test_main.py